version: '3.8'
services:
  jenkins:
    build:
      context: .
      args:
        - HOST_DOCKER_GID=998
    ports:
      - '127.0.0.1:8080:8080'
      - '127.0.0.1:50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
volumes:
  jenkins_home:
    external: false